# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hackeando
email: abner.terribili@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Developer at Elo7, cyclist and another to try to save the world.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: aterribili
github_username: aterribili

# Build settings
markdown: kramdown
